setwd("~/Bioinformatics MSc UCPH/0_MasterThesis/TCGAbiolinks/CBL_scripts/data/DEA/downregulation_trend/")
source("../../../functions.R") 


# load data for complete stages ,DOWN 
## these are generated by function 'DEA_MTC_save'
stage4down<- as.vector(read.table("Stage4vsNorm_down.txt"))$V1
stage3down<- as.vector(read.table("Stage3vsNorm_down.txt"))$V1
stage2down<- as.vector(read.table("Stage2vsNorm_down.txt"))$V1
stage1down<- as.vector(read.table("Stage1vsNorm_down.txt"))$V1

## PAM50 (update PAM50 names)
stage4down<- as.vector(read.table("LuminalA.stage4vsNorm_down.txt"))$V1
stage3down<- as.vector(read.table("LuminalA.stage3vsNorm_down.txt"))$V1
stage2down<- as.vector(read.table("LuminalA.stage2vsNorm_down.txt"))$V1
stage1down<- as.vector(read.table("LuminalA.stage1vsNorm_down.txt"))$V1
################
stage4down<- as.vector(read.table("LuminalB.stage4vsNorm_down.txt"))$V1
stage3down<- as.vector(read.table("LuminalB.stage3vsNorm_down.txt"))$V1
stage2down<- as.vector(read.table("LuminalB.stage2vsNorm_down.txt"))$V1
stage1down<- as.vector(read.table("LuminalB.stage1vsNorm_down.txt"))$V1

stage4down<- as.vector(read.table("BasalLike.stage4vsNorm_down.txt"))$V1
stage3down<- as.vector(read.table("BasalLike.stage3vsNorm_down.txt"))$V1
stage2down<- as.vector(read.table("BasalLike.stage2vsNorm_down.txt"))$V1
stage1down<- as.vector(read.table("BasalLike.stage1vsNorm_down.txt"))$V1

stage4down<- as.vector(read.table("HER2enriched.stage4vsNorm_down.txt"))$V1
stage3down<- as.vector(read.table("HER2enriched.stage3vsNorm_down.txt"))$V1
stage2down<- as.vector(read.table("HER2enriched.stage2vsNorm_down.txt"))$V1
stage1down<- as.vector(read.table("HER2enriched.stage1vsNorm_down.txt"))$V1

stage3down<- as.vector(read.table("NormalLike.stage3vsNorm_down.txt"))$V1
stage2down<- as.vector(read.table("NormalLike.stage2vsNorm_down.txt"))$V1
stage1down<- as.vector(read.table("NormalLike.stage1vsNorm_down.txt"))$V1
###########

# get only autophagy genes  
# per stage
autophagy_downreg_stages <- list(Stage4= sharedWithAuto(stage4down), #c("x"),#
                                 Stage3= sharedWithAuto(stage3down),
                                 Stage2= sharedWithAuto(stage2down),
                                 Stage1= sharedWithAuto(stage1down))
all_genes<-c()
for (i in names(autophagy_downreg_stages)){
  all_genes <- unique(sort(append(all_genes, autophagy_downreg_stages[[i]])))
}
length(all_genes)
all_genes

write( all_genes , file = "all_autodown_genes_mfuzz_group1_eachVSnormal_HER2.txt", sep="\n")


#per subtype

# per stage
stage4downLumA<- as.vector(read.table    ("LuminalA.stage4vsNorm_down.txt"))$V1
stage4downLumB<- as.vector(read.table    ("LuminalB.stage4vsNorm_down.txt"))$V1
stage4downBasal<- as.vector(read.table  ("BasalLike.stage4vsNorm_down.txt"))$V1
stage4downHER2<- as.vector(read.table("HER2enriched.stage4vsNorm_down.txt"))$V1
#stage3downNormL<- as.vector(read.table ("NormalLike.stage3vsNorm_down.txt"))$V1

autophagy_downreg_stage_PAM50 <- list(LuminalA= sharedWithAuto (stage4downLumA), 
                                      LuminalB= sharedWithAuto (stage4downLumB),
                                      BasalLike= sharedWithAuto(stage4downBasal),
                                      HER2enriched= sharedWithAuto(stage4downHER2))
                                    #NormalLike = sharedWithAuto (stage3downNormL))

all_genes<-c()
for (i in names(autophagy_downreg_stage_PAM50)){
  all_genes <- unique(sort(append(all_genes, autophagy_downreg_stage_PAM50[[i]])))
}
length(all_genes)
all_genes


library(VennDiagram)
### for stages (4 leaves)
dev.off()
venn <- venn.diagram(autophagy_downreg_stages, 
             category.names = c("Stage 4", "Stage 3","Stage 2","Stage 1"),
             #category.names = c( "Stage 3","Stage 2","Stage 1"),
             filename = NULL, lwd = 0.5,
             main = "Overlap of downregulated autophagy genes\n in stages of Basal-like subtype",
             main.cex=1.2,
             main.fontface = "bold",
             
             col = "transparent", 
             fill=c("cornflowerblue","green2","yellow","darkorchid1"),
             alpha =0.5,
             label.col = c("orange", "white", "darkorchid4", "white", "white", 
                           "white",    "white", "white", "darkblue", "white", "white", "white", "white", 
                           "darkgreen", "white"), 
             fontfamily = "serif",
             fontface = "bold",
             cat.fontface = "bold",
             cat.col = c("darkblue", "darkgreen", "orange", "darkorchid4"), 
             sub.cex = 2,
             cat.cex=1.2,
             cat.fontfamily = 'serif',
            
             #rotation.degree = 270,
             #margin = -0.02,
             cex=1.3)


grid.draw(venn)
dev.off()
########


#get genes
library(gplots)
ItemsList <- venn(autophagy_downreg_stages, show.plot=F)
ItemsList

colnames(ItemsList)



#### for PAM50 (5 leaves)
dev.off()
venn <- venn.diagram(autophagy_downreg_stage_PAM50, 
                     category.names = names(autophagy_downreg_stage_PAM50),
                     filename = NULL, lwd = 0.5,
                     main = "Venn10: Downregulated authophagy genes in stage4 in PAM50 subtypes", main.cex=1,
                     fill=c("turquoise", "salmon", "blue", "yellow"),#, "green"),
                     col = "transparent",
                     #label.col =c("grey"),
                     alpha =0.5,
                     label.cex = 1,
                     cat.just=list(c(0.6,1) , c(0,-4) , c(1,0) , c(1,1) ),#, c(0.8,-3)),
                     sub.cex = 3,
                     cat.cex=0.8, #group names
                     cat.fontfamily = 'sans',
                     cex=1)
grid.draw(venn)
dev.off()


#get genes
library(gplots)
ItemsList <- venn(autophagy_downreg_stage_PAM50, show.plot=F)
ItemsList



################# Mfuzz results

#load data
setwd("~/Bioinformatics MSc UCPH/0_MasterThesis/TCGAbiolinks/CBL_scripts/data/mfuzz_reproduced_final/final_for_report")

#all samples
#autogenes229_all_samp_all_genes_7clus<-as.vector(read.table("229_allgenes_allsamples_autophagy_down_cluster.txt", sep='\n'))$V1
#<-as.vector(read.table("158_group1_allsamples_autophagy_down_cluster.txt", sep='\n'))$V1
#autogenes132_all_samp_group1_9clus<-as.vector(read.table("132_group1_allsamples_autophagy_down_cluster.txt", sep='\n'))$V1
#autogenes146_all_samp_group1_8clus<-as.vector(read.table("146_group1_allsamples_autophagy_down_cluster.txt", sep='\n'))$V1
#autogenes166_all_samp_group1_8clus<-as.vector(read.table("166_group1_logRPKMbatch_allsamples_autophagy_down_cluster.txt", sep='\n'))$V1


#lumA
#autogenes_LumA_group1_8clus<-as.vector(read.table("138_group1_LumA_autophagy_down_cluster_notsign.txt", sep='\n'))$V1
#autogenes_LumB_group1_8clus<-as.vector(read.table("100_group1_LumB_autophagy_down_cluster_notsign.txt", sep='\n'))$V1
#autogenes_Basal_group1_8clus<-as.vector(read.table("100_group1_Basal_autophagy_down_cluster_notsign.txt", sep='\n'))$V1
#autogenes_HER2_group1_8clus<-as.vector(read.table("108_group1_HER2_autophagy_down_cluster_notsign.txt", sep='\n'))$V1
#autogenes_NormLike_group1_8clus<-as.vector(read.table( "24_group1_NormLike_autophagy_down_cluster_notsign.txt", sep='\n'))$V1

#autogenes_Ductal_group1_8clus<-as.vector(read.table( "135_group1_allsamples_Ductal_autophagy_down_cluster.txt", sep='\n'))$V1


cluster_all<-as.vector(read.table("264_group1_15k6cl_logRPKMbatch_allsamples_autophagy_down_cluster.txt", sep="\n"))$V1
cluster_basal<-as.vector(read.table("177_group1_15k6cl_logRPKMbatch_Basal_autophagy_down_cluster.txt", sep="\n"))$V1
cluster_lumA<-as.vector(read.table("210_group1_15k6cl_logRPKMbatch_LumA_autophagy_down_cluster.txt", sep="\n"))$V1
cluster_lumB<-as.vector(read.table("155_group1_15k6cl_logRPKMbatch_LumB1_autophagy_down_cluster.txt", sep="\n"))$V1
cluster_HER2<-as.vector(read.table("133_group1_15k6cl_logRPKMbatch_HER2_autophagy_down_cluster.txt", sep="\n"))$V1
cluster_normlike<-as.vector(read.table("59_group1_15k6cl_logRPKMbatch_normlike_autophagy_down_cluster.txt", sep="\n"))$V1


test_list<- list(LuminalA= cluster_lumA,
                 LuminalB= cluster_lumB,
                 BasalLike=cluster_basal,
                 HER2enriched=cluster_HER2,
                 #all=cluster_all)
                 NormalLike =cluster_normlike)

# venn for 5
##### THIS IS OK
dev.off()
venn <- venn.diagram(test_list[1:5], 
                     #category.names = names(test_list)[1:5],
                     category.names = c("Luminal A", "Luminal B", "Basal-like", "HER2-enriched", "Normal-like"),
                     filename = NULL, lwd = 1,
                     main = "Overlap of autophagy genes in downregulation clusters in PAM50 subtypes",
                     main.cex=1.1,
                     fill=c("cornflowerblue","green","yellow","darkorchid1", "turquoise"),
                     
                     label.col = c("darkblue", "darkgreen", "orange", "darkorchid4", "turquoise4",
                                   "black" ,"black" ,"black" ,"black" ,"black", 
                                   "black" ,"black" ,"black" ,"black","black" ,
                                   "black", "black" ,"black" ,"black" ,"black",
                                   "black" ,"black" ,"black" ,"black" ,"black" ,
                                   "black" ,"black" ,"black" ,"black","black" ,"white"), 
                     
                     col = "transparent",
                     alpha =0.5,
                     label.cex = 1,
                     cat.just=list(c(0.6,1) , c(0,-4) , c(1.2,-2) , c(1,1) , c(0.8,-3)),
                     cat.cex=1.2, #group names
                     cat.fontfamily = 'serif',
                     fontfamily = "serif",
                     fontface = "bold",
                     main.fontface = "bold",
                     cat.col = c("darkblue", "darkgreen", "orange", "darkorchid4", "turquoise4"), 
                     sub.cex = 3, #my was 3
                     cex=1.2)


grid.draw(venn)
dev.off()

## other cols


library(scales)
source_cols<-c( "#F0E442", "orangered3", "#E69F00", "royalblue3",  "#CC79A7")
show_col(source_cols)
venn <- venn.diagram(test_list[1:5], 
                     #category.names = names(test_list)[1:5],
                     category.names = c("Luminal A", "Luminal B", "Basal-like", "HER2-enriched", "Normal-like"),
                     filename = NULL, lwd = 1,
                     main = "Overlap of autophagy genes in downregulation clusters in PAM50 subtypes",
                     main.cex=1.1,
                     fill=c("#F0E442", "orangered3", "#E69F00", "royalblue3",  "#CC79A7"),
                     
                     #label.col = c("goldenrod3", "orangered4", "darkorange3" ,"royalblue3",  "#CC79A7",
                     #              "black" ,"black" ,"black" ,"black" ,"black", 
                     #              "black" ,"black" ,"black" ,"black","black" ,
                     #              "black", "black" ,"black" ,"black" ,"black",
                     #              "black" ,"black" ,"black" ,"black" ,"black" ,
                     #              "black" ,"black" ,"black" ,"black","black" ,"white"), 
                     
                     #col = "transparent",
                     alpha =c(0.8,0.6,0.8,0.8,0.5),
                     label.cex = 1,
                     cat.just=list(c(0.6,1) , c(0,-4) , c(1.2,-2) , c(1,1) , c(0.8,-3)),
                     cat.cex=1.2, #group names
                     cat.fontfamily = 'serif',
                     fontfamily = "serif",
                     fontface = "bold",
                     main.fontface = "bold",
                     cat.col = c("goldenrod3", "orangered4", "darkorange3" ,"royalblue3",  "#CC79A7"), 
                     sub.cex = 3, #my was 3
                     cex=1.1)
grid.draw(venn)
dev.off()
library(gplots)
ItemsList_clusterdata <- venn(test_list, show.plot=F)
ItemsList_clusterdata


basal_unique<-c("PLBD2" ,  "OSBPL7" ,"OSBPL8" ,"LIPA"   ,"EEA1"    ,"RABEP1" , "DNM1"    ,"STAB1"  ,
                "SNX9"  ,  "STON2"  ,"SYTL2"  ,"STX8"   ,"RAB14"   ,"PIK3C2G", "NEDD4"   ,"INPP4B" ,
                 "RAB24" ,  "ANKFY1", "GCC2"  , "MLPH"  , "MYO5C"  , "SYTL4" ,  "ZFYVE27", "FIS1"   ,
                 "SMCR7",   "WDFY3" , "CAPNS1", "PXN"   , "HSPB8"  , "BAD"   ,  "SREBF1" , "FOXA1"  ,
                 "XBP1" ,   "FGFR1" , "FGF1"  , "NGFR"  , "ITGB3"  , "PRR5"  ,  "EGLN2"  , "TMEM127",
                 "CTSO"  ,  "PRCP"  , "CD63"  , "EPDR1" , "TMEM192", "SPHK2" ,  "TMEM55B", "GNS"    ,
                 "ARSD"  ,  "ARSG"  , "GALC"  , "BLOC1S1")




test_list<- list(#genes229=autogenes229_all_samp_all_genes_7clus,
                 #all_samples=autogenes146_all_samp_group1_8clus,
                 all_samples=autogenes166_all_samp_group1_8clus,
                 #ductal=autogenes_Ductal_group1_8clus,
                 #genes158=autogenes158_all_samp_group1_7clus,
                 #genes132=autogenes132_all_samp_group1_9clus,
                 #LumA= autogenes_LumA_group1_8clus,
                 #LumB= autogenes_LumB_group1_8clus,
                 #Basal= autogenes_Basal_group1_8clus,
                 #HER2= autogenes_HER2_group1_8clus)
                 #NormLike= autogenes_NormLike_group1_8clus)
                 dea_genes=all_genes)
dev.off()
venn <- venn.diagram(test_list, 
                     category.names = names(test_list),
      # category.names = c("Autophagy genes in downreglated cluster\n from Group1 DE genes, Normal-like only",
       #                   "Downregulated authopagy genes in all stages in Normal-like \n vs normal (Group1 model)"),
       filename = NULL, lwd = 0.5,
       main = NULL, main.cex=1.5, main.pos = c(0.3,0.8),
       fill=c("turquoise", "salmon"),# "blue", "purple"),
       col = "transparent",
       alpha =0.5,
       label.cex = 2,
       #cat.just=list(c(0,4) , c(1,8)), #LumA
       #cat.just=list(c(1.3,-4) , c(0,-1)), #LumB
       sub.cex = 2,
       cat.cex=0.7, #group names
       cat.fontfamily = 'sans',
       cex=2)
grid.draw(venn)
dev.off()

#get genes
library(gplots)
ItemsList <- venn(test_list, show.plot=F)
ItemsList

save(ItemsList, file="overlap_down_DEA_mfuzz_NormLike.rda")

genes146<- c("OSBPL9"  ,  "LPL"     , "LCAT"     , "LIPE"     , "MGLL"    , "DAGLA"  ,  "MTMR10"   , "PIK3R1"   ,
           "MTMR3"   ,  "PTEN"    , "MTMR12"   , "PIK3C2B"  , "EEA1"    , "ARL4C"  ,  "BIN1"     , "SNX33"    ,
            "SH3KBP1",   "SNX1"   ,  "SNX18"   ,  "DNM1"    ,  "SNCA"   ,  "SCARF1",   "MRC1"    ,  "LRP3"     ,
            "STAB1"  ,   "STAB2"  ,  "SNX9"    ,  "CDH13"   ,  "EHD2"   ,  "ABCA1" ,   "VPS36"   ,  "RILP"     ,
            "ADRB2"  ,   "LYST"   ,  "PIK3C2G" ,  "SYNRG"   ,  "INPP5K" ,  "FYCO1" ,   "ITSN1"   ,  "RAB11FIP2",
            "RAMP2"  ,   "STX11"  ,  "SPG20"   ,  "IQSEC3"  ,  "IQSEC1" ,  "PIKFYVE",   "RAB11B" ,   "CAV2"     ,
            "ARAP3"  ,   "OSBPL1A",  "VPS11"   ,  "SH3TC2"  ,  "APPL2"  ,  "ANKFY1",   "DENND5A" ,  "LEPR"     ,
            "MYRIP"  ,   "PLEKHM1",  "TBC1D2B" ,  "UACA"    ,  "PINK1"  ,  "TBC1D17",   "PARK2"  ,   "FOXO1"    ,
            "PPARG"  ,   "PPARA"  ,  "MAP1LC3C",  "ATG2A"   ,  "WDFY3"  ,  "TLR4"  ,   "SH3GLB1" ,  "RHOQ"     ,
            "DAPK2"  ,   "PXN"    ,  "HSPA12A" ,  "MITF"    ,  "EGR1"   ,  "MYC"   ,   "JUNB"    ,  "NFE2L1"   ,
            "RXRA"   ,   "ATF3"   ,  "NR3C1"   ,  "MEF2C"   ,  "FOS"    ,  "ZEB1"  ,   "EPAS1"   ,  "JUN"      ,
            "TP63"   ,   "ESR2"   ,  "STAT6"   ,  "CYR61"   ,  "SRF"    ,  "LMX1A" ,   "FLT1"    ,  "IGF1"     ,
            "IL1R1"  ,   "VEGFB"  ,  "FGF2"    ,  "TGFBR2"  ,  "FGF1"   ,  "HSPG2" ,   "TGFBR3"  ,  "KDR"      ,
            "NGFR"   ,   "TEK"    ,  "ITGA3"   ,  "ITGA1"   ,  "FLT4"   ,  "IRS2"  ,   "NTRK2"   ,  "FGF7"     ,
            "EGF"    ,   "CR1"    ,  "TSC1"    ,  "PRR5"    ,  "PRKAA1" ,  "PRKCH" ,   "MRAS"    ,  "RRAS"     ,
            "MARK1"  ,   "YAP1"   ,  "MAP3K3"  ,  "HERC1"   ,  "HDAC5"  ,  "HDAC7" ,   "HDAC4"   ,  "SGK1"     ,
            "SCPEP1" ,   "CTSG"   ,  "HPS1"    ,  "TPCN1"   ,  "CLCN6"  ,  "EPDR1" ,   "ABCA5"   ,  "DAB2"     ,
            "TRIM23" ,   "LGMN"   ,  "SIDT2"   ,  "PLD1"    ,  "LMBRD1" ,  "DPP4"  ,   "PCYOX1"  ,  "STS"      ,
           "HYAL1",  "RAB43")
length(genes146)
sharedWithAutoCORE(genes146)->x
####  using bioMart to retrive gene functions
library(biomaRt)
ensembl=useMart("ensembl") #query ensembl via biomart
ensembl = useDataset("hsapiens_gene_ensembl",mart=ensembl) #get human

#see what filtrers and attributes you can query :
filters = listFilters(ensembl)
attributes = listAttributes(ensembl)

goids = getBM(
  
  #you want hgnc_symbol so you know which is what, the GO ID and
  # name_1006 is actually the identifier of 'Go term name'
  attributes=c('hgnc_symbol', "description","name_1006" ,"go_id"), 
  
  filters='hgnc_symbol', 
  values=genes146, 
  mart=ensembl)

head(goids)

library(dplyr)
report = filter(goids, !go_id == "") %>%
  group_by(hgnc_symbol) %>%
  summarize(description = do.call(paste, c(as.list(description), sep=",")),
            go_ids = do.call(paste, c(as.list(go_id), sep=",")),
            go_names = do.call(paste, c(as.list(name_1006), sep=",")))

View(report)
write.csv(report, file= "downreg_autophagy146_genelist.csv", col.names = TRUE, row.names = FALSE)



gn11<-c("LPL"   ,   "LIPE"    , "ITSN1" ,   "STX11"  ,  "IQSEC3"  , "CAV2"  ,   "MAP1LC3C", "RHOQ"   ,  "ESR2" ,   
         "MRAS"    , "MARK1" )
sharedWithAutoCORE(gn11)
